version: 0.1

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --silent --progress-false
      - npm --version
  build:
    commands:
      - echo Dev Build started on `date`
      - npm run dist:dev
  post_build:
    commands:      
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths /*
artifacts:
  files:
    - '**/*'
  base-directory: build